### ISSUE TITLE
HTML minify conflicts with Varnish caching

### ISSUE THREAD

**Issue by m-overlund** [fooman/speedsteradvanced#26]
If i enable HTML minify, the whole header section disappears from all our sites (using different themes).

Example:
https://www.fyr-selv.dk/taendbreve.html

![header-dissapears](https://user-images.githubusercontent.com/504236/32376359-e49a1ea0-c0a4-11e7-9db9-03257f4921a0.png)

It seems to be a conflict with Varnish (via Turpentine https://github.com/nexcess/magento-turpentine), as it doesn't occur in the checkout flow, which isn't being cached. Also if i bypass Varnish, it displays correctly.

The whole header section isn't present in the outputted html.
The header section get's cached seperately via ESI hole-punching to display the dynamic contents properly.

**Comment by sprankhub** [comment]
I can confirm this issue. I had this issue with two clients, which use Varnish, as well.

Unfortunately, I could not fix it yet.

**Comment by Quazz** [comment]
I have this happening, we don't use Varnish, but we do use Lesti FPC.

**Comment by sprankhub** [comment]
@Quazz any more information how I can reproduce it with Lesti FPC? It seems to work for me in combination with Lesti...

**Comment by sprankhub** [comment]
Ah now I got it. If you define e.g. your header as a dynamic block in Lesti FPC, the header disappears. Will look into that.

**Comment by sprankhub** [comment]
#27 should fix your issue. Could you verify @Quazz @m-overlund?

**Comment by m-overlund** [comment]
Doesn't fix the issues with Varnish

**Comment by sprankhub** [comment]
Are you 100% sure @m-overlund? You need to flush the cache in order to check if it is resolved (which may not be a good idea on a live system on black friday ^^)... By the way, flushing the cache via CLI did not work for me. I had to do it via the backend.

**Comment by m-overlund** [comment]
I've copied Model/Html.php and applied to change to Model/Observer.php and cleared the cache via the backend.
You can checkout the result at www.vognladet.dk - header and footer is missing

**Comment by sprankhub** [comment]
Weird. Is the header and footer loaded via ESI (https://github.com/nexcess/magento-turpentine/blob/8549a0f207c63e62c61570f81925bd574c63f2c5/app/design/frontend/base/default/template/turpentine/esi.phtml) or via AJAX (https://github.com/nexcess/magento-turpentine/blob/8549a0f207c63e62c61570f81925bd574c63f2c5/app/design/frontend/base/default/template/turpentine/ajax.phtml)?

**Comment by sprankhub** [comment]
@m-overlund could you answer my question? Would love to get this sorted.

**Comment by m-overlund** [comment]
We're using ESI

**Comment by sprankhub** [comment]
Thanks for your feedback. I just added another commit, which should fix the issue. I handled the `<!-- ESI` comments correctly, but missed the `<!--esi` comments. Could you please test again @m-overlund? It definitely fixes the issue in my test environment.

**Comment by m-overlund** [comment]
It seems to be fixed.
On one of our templates the footer still doesn't show, but i'll have to take a closer look to find out why.

The other templates works with both header and footer now.

**Comment by sprankhub** [comment]
Thanks for your instant feedback!

I think #27 is ready to merge @fooman!
